Prepend "Get" prefix to methods named "type".
This is needed to avoid conflicts like the one below:
../../third_party/WebKit/Source/web/WebDOMFileSystem.cpp:93:21:
error: member 'Type' found in multiple base classes of different types
  switch (private_->Type()) {
                    ^
../../third_party/WebKit/Source/modules/filesystem/DOMFileSystemBase.h:88:18:
note: member found by ambiguous name lookup
  FileSystemType Type() const { return type_; }
                 ^
../../third_party/WebKit/Source/core/dom/ContextLifecycleObserver.h:71:8:
note: member found by ambiguous name lookup
  enum Type {
       ^

BUG=582312

Review-Url: https://codereview.chromium.org/2648833002
Cr-Original-Commit-Position: refs/heads/master@{#445442}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: 877fb8bd29acf269d27688444a50c36f9332e946