[BRP] Add clang_use_chrome_plugins=false to raw_ptr rewriter's gn args
Additional plugin analysis ins't useful when running the tool, so
might as well save some time by disabling them.

More importantly, we need to turn them off to work around the error:
```
../../base/containers/checked_iterators.h:7:9: error: unknown pragma ignored [-Werror,-Wunknown-pragmas]
    7 | #pragma allow_unsafe_buffers
```
The pragmas are only added to the files if -DUNSAFE_BUFFERS_BUILD,
which is only supposed to be present if the plugin is there.

Change-Id: I9f5653a65553f55ca7c5d35f98f4f3f83aec4648
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5595498
Auto-Submit: Bartek Nowierski <bartekn@chromium.org>
Reviewed-by: danakj <danakj@chromium.org>
Commit-Queue: Bartek Nowierski <bartekn@chromium.org>
Reviewed-by: Daniel Cheng <dcheng@chromium.org>
Reviewed-by: Keishi Hattori <keishi@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1311558}
NOKEYCHECK=True
GitOrigin-RevId: ceda8abb46b954737157eb7f4298cf17d41576ea